// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJJoEQvGnlpUVarDbWVw20K4kjwDobSk4',
    appId: '1:1070821908373:web:ae2558947c6a5248b1609c',
    messagingSenderId: '1070821908373',
    projectId: 'synapse-9253c',
    authDomain: 'synapse-9253c.firebaseapp.com',
    storageBucket: 'synapse-9253c.firebasestorage.app',
    measurementId: 'G-RGN2M2QQE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3s6A64A1vmO_9Jop9cCYSSiDkBmITvS0',
    appId: '1:1070821908373:android:b719b2da1355fda9b1609c',
    messagingSenderId: '1070821908373',
    projectId: 'synapse-9253c',
    storageBucket: 'synapse-9253c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt2ghSxT9NKmRihak3i2qkc-huKrtM2Bo',
    appId: '1:1070821908373:ios:c10a65a4d2da0b40b1609c',
    messagingSenderId: '1070821908373',
    projectId: 'synapse-9253c',
    storageBucket: 'synapse-9253c.firebasestorage.app',
    iosBundleId: 'com.example.synapse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt2ghSxT9NKmRihak3i2qkc-huKrtM2Bo',
    appId: '1:1070821908373:ios:c10a65a4d2da0b40b1609c',
    messagingSenderId: '1070821908373',
    projectId: 'synapse-9253c',
    storageBucket: 'synapse-9253c.firebasestorage.app',
    iosBundleId: 'com.example.synapse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJJoEQvGnlpUVarDbWVw20K4kjwDobSk4',
    appId: '1:1070821908373:web:a07d158ee46556cab1609c',
    messagingSenderId: '1070821908373',
    projectId: 'synapse-9253c',
    authDomain: 'synapse-9253c.firebaseapp.com',
    storageBucket: 'synapse-9253c.firebasestorage.app',
    measurementId: 'G-H03YM6FZF8',
  );
}
